spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwtdb?useSSL=false
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  # App Properties
monapp:
    jwtSecret: andreKey
    jwtExpirationMs: 86400000